package com.university.management.model;

import jakarta.persistence.*;
import java.time.LocalDateTime;

/**
 * =====================================================
 * BASE ENTITY — Abstract Class
 * =====================================================
 *
 * OOP CONCEPTS DEMONSTRATED:
 * -------------------------------------------------
 * 1. ABSTRACTION:
 *    - This class is declared 'abstract' which means you CANNOT
 *      create a BaseEntity object directly.
 *    - It defines a TEMPLATE that all other entity classes follow.
 *    - Example: You can't do "new BaseEntity()" — but you CAN do
 *      "new Department()" because Department extends BaseEntity.
 *
 * 2. ENCAPSULATION:
 *    - All fields are 'private' — hidden from outside the class.
 *    - Access is only allowed through getter/setter methods.
 *    - This protects data integrity.
 *
 * 3. INHERITANCE:
 *    - Every entity class (Department, Course, etc.) will INHERIT
 *      from this class, automatically getting id, createdAt, updatedAt.
 *    - This avoids repeating the same code 6 times.
 * =====================================================
 */
@MappedSuperclass  // JPA: "Don't create a table for this class, share its fields with child classes"
public abstract class BaseEntity {

    // ---- ENCAPSULATION: private fields ----

    /**
     * Primary key — automatically generated by the database.
     * Every record gets a unique ID.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)  // Auto-increment in MySQL
    private Long id;

    /**
     * Timestamp when record was first created.
     * @Column(updatable = false) means this never changes after creation.
     */
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;

    /**
     * Timestamp when record was last modified.
     * Updated automatically every time we save the record.
     */
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    // ---- JPA Lifecycle Hooks ----

    /**
     * @PrePersist runs AUTOMATICALLY before a new record is saved to DB.
     * Sets both createdAt and updatedAt to the current time.
     */
    @PrePersist
    protected void onCreate() {
        this.createdAt = LocalDateTime.now();
        this.updatedAt = LocalDateTime.now();
    }

    /**
     * @PreUpdate runs AUTOMATICALLY before an existing record is updated in DB.
     * Updates the updatedAt timestamp.
     */
    @PreUpdate
    protected void onUpdate() {
        this.updatedAt = LocalDateTime.now();
    }

    // ---- ENCAPSULATION: Getters and Setters ----
    // These are the ONLY way to access/modify private fields from outside this class.

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }
}